'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {ladeKarte}=require('./laden');const {baueHass}=require('./geraet-attrappe');
function setup(extra={}) {const {BuschCardsCore}=ladeKarte(['BuschCardsCore'],{setTimeout,clearTimeout,queueMicrotask,performance,...extra});const c=new BuschCardsCore();const h=baueHass();c.seed(h);return {c,h};}
const spec={filter:{include:[{domain:'sensor',integration:'shelly',state:'< 20'}]}};
test('identical queries share one object and one computation',()=>{const {c}=setup();const q=c.query(spec);for(let i=0;i<25;i++)assert.equal(c.query(JSON.parse(JSON.stringify(spec))),q);assert.equal(q.metrics.calculations,1);assert.ok(q.result.includes('sensor.decke_leistung'));c.dispose();});
test('unrelated state change evaluates zero candidates and emits no result',()=>{const {c,h}=setup();const q=c.query(spec);let updates=0;const off=c.subscribe(q,()=>updates++);const before=q.metrics.evaluated;updates=0;c.updateState('light.decke',{...h.states['light.decke'],state:'off'});assert.equal(q.metrics.evaluated,before);assert.equal(updates,0);off();c.dispose();});
test('one relevant change evaluates one entity, enters/exits and suppresses unchanged result',()=>{const {c,h}=setup();const q=c.query(spec);let updates=0;const off=c.subscribe(q,()=>updates++);updates=0;const before=q.metrics.evaluated;c.updateState('sensor.decke_leistung',{...h.states['sensor.decke_leistung'],state:'13'});assert.equal(q.metrics.evaluated,before+1);assert.equal(updates,0);c.updateState('sensor.decke_leistung',{...h.states['sensor.decke_leistung'],state:'30'});assert.ok(!q.result.includes('sensor.decke_leistung'));assert.equal(updates,1);c.updateState('sensor.decke_leistung',{...h.states['sensor.decke_leistung'],state:'1'});assert.ok(q.result.includes('sensor.decke_leistung'));assert.equal(updates,2);off();c.dispose();});
test('new entities enter previously empty queries; removal exits',()=>{const {c}=setup();const q=c.query({filter:{include:[{domain:'weather'}]}});const off=c.subscribe(q,()=>{});c.updateState('weather.new',{state:'sunny',attributes:{}});assert.deepEqual([...q.result],['weather.new']);c.updateState('weather.new',null);assert.equal(q.result.length,0);off();c.dispose();});
test('25 subscribers to time filters use at most one timer and cross boundaries without states',()=>{
 let now=0,id=0;const timers=new Map();const {c}=setup({Date:class extends Date {static now(){return now;}},setTimeout:(fn,delay)=>{timers.set(++id,{fn,at:now+delay});return id;},clearTimeout:id=>timers.delete(id)});
 c.updateState('sensor.time',{state:'1',attributes:{},last_changed:new Date(0).toISOString()});
 const q=c.query({filter:{include:[{entity_id:'sensor.time',last_changed:'> 1 m ago'}]}});const offs=Array.from({length:25},()=>c.subscribe(q,()=>{}));assert.equal(q.result.length,0);assert.equal(timers.size,1);
 now=60001;const pending=[...timers.values()];timers.clear();pending.forEach(t=>t.fn());assert.deepEqual([...q.result],['sensor.time']);assert.equal(timers.size,0);offs.forEach(off=>off());assert.equal(timers.size,0);c.dispose();
});
test('unknown rules fail explicitly rather than returning guessed matches',()=>{const {c}=setup();assert.throws(()=>c.query({filter:{include:[{imaginary:'yes'}]}}),/rule/i);c.dispose();});
test('query mutation by one consumer cannot corrupt shared result',()=>{const {c}=setup();const q=c.query(spec);assert.throws(()=>q.result.push('sensor.injected'));c.dispose();});
test('unrelated events do not rebuild the shared time schedule',()=>{
 let count=0;const {c,h}=setup({setTimeout:()=>++count,clearTimeout:()=>{}});
 c.updateState('sensor.time',{state:'1',attributes:{},last_changed:new Date().toISOString()});const q=c.query({filter:{include:[{entity_id:'sensor.time',last_changed:'> 1 m ago'}]}});const off=c.subscribe(q,()=>{});const before=count;c.updateState('light.decke',{...h.states['light.decke'],state:'off'});assert.equal(count,before);off();c.dispose();
});
test('old handles subscribe to the current shared query without deleting active subscribers',()=>{const {c}=setup();const spec={filter:{include:[{domain:'weather'}]}};const old=c.query(spec);c.subscribe(old,()=>{})();const current=c.query(spec);let a,b;const offA=c.subscribe(current,v=>a=v);const offB=c.subscribe(old,v=>b=v);c.updateState('weather.test',{state:'sunny',attributes:{}});assert.deepEqual([...b],['weather.test']);offB();c.updateState('weather.next',{state:'sunny',attributes:{}});assert.equal(a.length,2);offA();c.dispose();});
test('throwing subscriber cannot break other subscribers or cleanup',()=>{const {c}=setup();const q=c.query({filter:{include:[{domain:'weather'}]}});const off=c.subscribe(q,()=>{throw Error('test');});let result;const other=c.subscribe(q,v=>result=v);c.updateState('weather.test',{state:'sunny',attributes:{}});assert.equal(result.length,1);off();other();assert.equal(c.engine.timer,null);c.dispose();});
