'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {ladeKarte}=require('./laden'),{baueHass}=require('./geraet-attrappe');
function setup(extra={}){const api=ladeKarte(['BuschCardsCore','devNormalisiereKonfig','BuschDeviceCard'],{performance,setTimeout,clearTimeout,...extra});const c=new api.BuschCardsCore(),h=baueHass();h.formatEntityState=s=>s.state;c.hass=h;c.seed(h);return {...api,c,h};}
const ids=q=>Array.from(q.result,r=>r.entity).sort();
test('device-scoped Smart rules cannot include another device',()=>{const {c}=setup();const q=c.smartQuery({filter:{include:[{domain:'sensor'}]}},'d1');assert.ok(ids(q).length);assert.ok(ids(q).every(id=>c.getEntity(id).device_id==='d1'));const other=c.smartQuery({filter:{include:[{entity_id:'sensor.aqara_temperatur'}]}},'d1');assert.equal(other.result.length,0);c.dispose();});
test('same device and rules share query; other devices stay independent',()=>{const {c}=setup(),cfg={filter:{include:[{entity_id:'*'}],exclude:[{state:'unavailable'}]}};assert.equal(c.smartQuery(cfg,'d1'),c.smartQuery(cfg,'d1'));assert.notEqual(c.smartQuery(cfg,'d1'),c.smartQuery(cfg,'d2'));const q=c.smartQuery(cfg,'d1'),off=c.subscribe(q,()=>{}),n=q.metrics.calculations;c.updateState('sensor.foreign',{entity_id:'sensor.foreign',state:'unavailable',attributes:{}});assert.equal(q.metrics.calculations,n);assert.ok(q.metrics.candidates<=c.getDeviceEntities('d1').length);off();c.dispose();});
test('state exclusion changes membership incrementally, nested rules use Smart semantics',()=>{const {c}=setup(),cfg={filter:{include:[{and:[{domain:'sensor'},{or:[{state:'> 5'},{state:'unavailable'}]}]}],exclude:[{state:'unavailable'}]}};const q=c.smartQuery(cfg,'d1'),off=c.subscribe(q,()=>{});assert.ok(ids(q).includes('sensor.decke_leistung'));c.updateState('sensor.decke_leistung',{...c.hass.states['sensor.decke_leistung'],state:'unavailable'});assert.ok(!ids(q).includes('sensor.decke_leistung'));c.updateState('sensor.decke_leistung',{...c.hass.states['sensor.decke_leistung'],state:'30'});assert.ok(ids(q).includes('sensor.decke_leistung'));off();c.dispose();});
test('age filters use the existing shared timer and release it',()=>{let active=0;const {c}=setup({setTimeout:()=>{active++;return 1},clearTimeout:()=>{active--}});c.updateState('sensor.decke_leistung',{...c.hass.states['sensor.decke_leistung'],last_changed:new Date().toISOString()});const cfg={filter:{include:[{last_changed:'< 1'}]}};const q=c.smartQuery(cfg,'d1'),off1=c.subscribe(q,()=>{}),off2=c.subscribe(c.smartQuery(cfg,'d1'),()=>{});assert.equal(active,1);off1();assert.equal(active,1);off2();assert.equal(active,0);c.dispose();});
test('device filter config is cloned, nested predicates supported, malformed filters rejected',()=>{const {c,devNormalisiereKonfig:n}=setup();const cfg={device_id:'d1',filter:{include:[{or:[{state:'on'},{attributes:{device_class:'battery'}}]}],exclude:[{not:{domain:'sensor'}}]}};const a=n(cfg);a.filter.include[0].or[0].state='off';assert.equal(cfg.filter.include[0].or[0].state,'on');for(const filter of [{include:{}},{exclude:[null]},{include:[{or:'x'}]},{include:[{unknown:'x'}]},{template:'x'}])assert.throws(()=>n({device_id:'d1',filter}));c.dispose();});
test('filter chips never appear in the runtime card',()=>{const {c,BuschDeviceCard}=setup();const card=new BuschDeviceCard();card._config={labels:['ignore'],labels_hide:['ignore']};card._chips={textContent:'ignore',hidden:false};card._zeichneChips();assert.equal(card._chips.textContent,'');assert.equal(card._chips.hidden,true);c.dispose();});

test('registry device moves remove entities from an existing scoped query',()=>{const {c,h}=setup();const q=c.smartQuery({filter:{include:[{domain:'sensor'}]}},'d1'),off=c.subscribe(q,()=>{});assert.ok(ids(q).includes('sensor.decke_leistung'));h.entities['sensor.decke_leistung']={...h.entities['sensor.decke_leistung'],device_id:'d2'};c.seed(h);assert.ok(!ids(q).includes('sensor.decke_leistung'));off();c.dispose();});
test('external group membership still refreshes a scoped predicate',()=>{const {c}=setup();c.updateState('group.dynamic',{entity_id:'group.dynamic',state:'on',attributes:{entity_id:['sensor.decke_leistung']}});const q=c.smartQuery({filter:{include:[{group:'group.dynamic'}]}},'d1'),off=c.subscribe(q,()=>{});assert.deepEqual(ids(q),['sensor.decke_leistung']);c.updateState('group.dynamic',{entity_id:'group.dynamic',state:'on',attributes:{entity_id:[]}});assert.equal(q.result.length,0);off();c.dispose();});
