'use strict';
const {ladeKarte}=require('./laden');
class Element {
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.childNodes=this.children;this.attributes={};this.listeners={};this.style={};this.dataset={};this.isConnected=false;}
 attachShadow(){return this.shadowRoot=new Element();} append(...nodes){this.children.push(...nodes);} appendChild(n){this.append(n);return n;} replaceChildren(...n){this.children=n;this.childNodes=n;} setAttribute(k,v){this.attributes[k]=String(v);} getAttribute(k){return this.attributes[k];} removeAttribute(k){delete this.attributes[k];} addEventListener(k,fn){this.listeners[k]=fn;} dispatchEvent(e){this.event=e;return true;} querySelector(){return null;} querySelectorAll(){return [];} get firstChild(){return this.children[0];}
}
function load(overrides={}){const registered=new Map(),window={customCards:[],confirm:()=>true},document={createElement:tag=>new Element(tag)};const names=['BuschCardsCore','BuschFritzDeviceCard','BuschNetworkCard','BuschFritzDeviceEditor','BuschNetworkEditor','BuschNetworkClientResolver','BuschNetworkQueries','buschFritzModel','buschNetworkIPv4','buschNetworkCIDR','buschNetworkRule','buschNetworkTime','buschNetworkCompare','buschNetworkConfig','buschNetworkSchema','BUSCH_NETWORK_TEXT','BUSCH_NETWORK_DEFAULTS','buschNetworkAvailable','BuschNetworkClock:typeof BuschNetworkClock==="undefined"?null:BuschNetworkClock'];return {...ladeKarte(names,{HTMLElement:Element,document,window,navigator:{language:'de'},performance,setTimeout,clearTimeout,CustomEvent:class{constructor(type,init){this.type=type;Object.assign(this,init);}},customElements:{get:k=>registered.get(k),define:(k,v)=>registered.set(k,v)},...overrides}),registered,window};}
function fixture(l){const core=new l.BuschCardsCore(),devices={router:{id:'router',name:'Example router',model:'Router',identifiers:[['fritz','box-key']],config_entries:['entry']},other:{id:'other',name:'Other',identifiers:[['fritz','other-key']],config_entries:['other-entry']},client:{id:'client',name:'Workstation',config_entries:['entry']},ap:{id:'ap',name:'Example access point',identifiers:[['fritz','ap-key']],config_entries:['entry']}};const entities={},states={};const add=(id,device,unique_id,state='on',attributes={},platform='fritz',entry='entry')=>{entities[id]={entity_id:id,device_id:device,unique_id,platform,config_entry_id:entry};states[id]={entity_id:id,state,attributes,last_changed:'2026-09-29T10:00:00Z',last_updated:'2026-09-29T10:00:00Z'};return id;};
 add('binary_sensor.renamed','router','box-key-is_connected');add('button.renamed','router','box-key-reboot','unknown');add('sensor.start','router','box-key-device_uptime','2026-09-29T00:00:00Z');add('sensor.temperature','router','box-key-cpu_temperature','42',{unit_of_measurement:'°C'});add('sensor.rate','router','box-key-kb_s_received','100',{unit_of_measurement:'kB/s'});add('switch.radio','router','box-key-wi_fi_1');add('update.native','router','box-key-update','on',{supported_features:1,installed_version:'1',latest_version:'2'});
 const mac='02:00:00:00:00:01';add('device_tracker.renamed','client',mac+'_tracker','home',{source_type:'router',mac,ip:'192.0.2.10',host_name:'example-host',friendly_name:'Workstation',last_time_reachable:'2026-09-29T12:00:00Z'});add('switch.internet','client',mac+'_internet_access','off');add('button.wake','client',mac+'_wake_on_lan','unknown');const hass={devices,entities,states,locale:{language:'en'},user:{is_admin:true}};core.seed(hass);return {core,hass,add,entities,states,devices,refresh:()=>core.seed(hass)};}
module.exports={load,fixture,Element};
