'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {ladeKarte}=require('./laden');
const api=ladeKarte(['BuschCardsCore','buschSmartCardConfig','buschSmartConfig','buschSmartResult'],{performance,setTimeout,clearTimeout});
const clean=x=>JSON.parse(JSON.stringify(x));
function setup(){const c=new api.BuschCardsCore(),h={states:{},entities:{},devices:{},areas:{},formatEntityState:s=>s.state};
 for(let i=0;i<9;i++){h.devices['d'+i]={id:'d'+i,name:'Device '+(8-i)};for(let j=0;j<3;j++){const id=`sensor.e${i}_${j}`;h.states[id]={entity_id:id,state:'unavailable',attributes:{friendly_name:`Entity ${i} ${j}`,nested:{value:{items:[i]}}}};h.entities[id]={entity_id:id,device_id:'d'+i,platform:'demo'};}}
 h.states['sensor.orphan']={entity_id:'sensor.orphan',state:'unavailable',attributes:{friendly_name:'Orphan'}};
 c.hass=h;c.seed(h);return {c,h};}
const config={filter:{include:[{state:'unavailable'}]},value:{type:'device_id',missing:'skip'},unique_values:true,sort:{method:'name',count:6},card:{type:'vertical-stack'},card_param:'cards',item:{type:'custom:busch-device-card',start_expanded:false,groups_open:[],nested:{list:[{fixed:true}]}},item_param:'device_id'};
test('mapper makes six unique device cards after missing handling and pagination',()=>{const {c}=setup();const q=c.smartQuery(config),out=api.buschSmartCardConfig(config,q.result);assert.equal(out.type,'vertical-stack');assert.equal(out.cards.length,6);assert.deepEqual(clean(out.cards.map(x=>x.device_id)),['d0','d1','d2','d3','d4','d5']);assert.ok(out.cards.every(x=>x.type==='custom:busch-device-card'&&x.start_expanded===false));out.cards[0].nested.list[0].fixed=false;out.cards[0].groups_open.push('x');assert.equal(out.cards[1].nested.list[0].fixed,true);assert.equal(config.item.nested.list[0].fixed,true);assert.equal(out.cards[1].groups_open.length,0);c.dispose();});
test('generic entity tile and nested object values are cloned independently',()=>{const tile=api.buschSmartCardConfig({...config,item:{type:'tile'},item_param:'entity'},['sensor.a']);assert.equal(tile.cards[0].entity,'sensor.a');const value={items:[1]},cfg={...config,item:{type:'custom:example',config:{keep:true}},item_param:'config.target'};const out=api.buschSmartCardConfig(cfg,[value,value]);assert.deepEqual(clean(out.cards[0].config),{keep:true,target:value});out.cards[0].config.target.items.push(2);assert.deepEqual(clean(out.cards[1].config.target.items),[1]);assert.deepEqual(value.items,[1]);});
test('without item raw output and legacy target precedence remain unchanged',()=>{const {item,item_param,...cfg}=config;assert.deepEqual(clean(api.buschSmartCardConfig(cfg,['d0']).cards),['d0']);assert.deepEqual(clean(api.buschSmartCardConfig({...cfg,card:{type:'entities',cards:['static']}},['d0']).cards),['static']);});
test('mapped cards replace an empty container editor placeholder',()=>{const out=api.buschSmartCardConfig({...config,card:{type:'vertical-stack',cards:[]}},['d0']);assert.equal(out.cards[0]?.device_id,'d0');});
test('mapping stays outside shared projection cache',()=>{const {c}=setup();assert.equal(c.smartQuery(config),c.smartQuery({...config,item:{type:'tile'},item_param:'entity'}));assert.notDeepEqual(clean(api.buschSmartCardConfig(config,['d0'])),clean(api.buschSmartCardConfig({...config,item:{type:'tile'},item_param:'entity'},['d0'])));c.dispose();});
test('device_name uses registry names while name keeps entity semantics',()=>{const {c,h}=setup();assert.deepEqual(clean(c.smartQuery({...config,sort:{method:'device_name',count:2}}).result),['d8','d7']);h.devices.d0.name_by_user='AAA';c.seed(h);assert.deepEqual(clean(c.smartQuery({...config,sort:{method:'device_name',count:2}}).result),['d0','d8']);assert.deepEqual(clean(c.smartQuery({...config,sort:{method:'name',first:1,count:2}}).result),['d1','d2']);c.dispose();});
test('invalid item templates and unsafe or conflicting paths fail clearly',()=>{for(const patch of [{item:[]},{item:null},{item:'x'},{item:{}},{item_param:''},{item_param:'a..b'},{item_param:'config.0.entity'},{item_param:'__proto__.polluted'},{item_param:'config.constructor.prototype.x'},{item_param:'nested.list.x.y'}])assert.throws(()=>api.buschSmartConfig({...config,...patch}));assert.equal({}.polluted,undefined);});
test('debug trace explains source, value, missing, duplicate and selected values',()=>{const {c}=setup(),trace={};const rows=api.buschSmartResult(c,config,[],null,trace);assert.equal(trace.missing,1);assert.equal(trace.duplicates,18);assert.equal(trace.projected,9);assert.equal(trace.output,6);assert.ok(trace.rows.some(r=>r.source==='sensor.e0_0'&&r.value==='d0'&&r.status==='selected'));assert.ok(trace.rows.some(r=>r.source==='sensor.e0_1'&&r.status==='duplicate'));assert.equal(rows.length,6);c.dispose();});
