'use strict';const test=require('node:test'),assert=require('node:assert/strict');const {ladeKarte}=require('./laden');
test('smart config validates rules and preserves auto-entities import',()=>{const {buschSmartConfig}=ladeKarte(['buschSmartConfig']);const c=buschSmartConfig({type:'custom:auto-entities',entities:['sensor.a'],card:{type:'glance'}});assert.equal(c.type,'custom:busch-smart-entities');assert.equal(c.card.type,'glance');assert.throws(()=>buschSmartConfig({filter:{include:[{imaginary:'x'}]}}),/imaginary/);});
test('smart target config preserves upstream card parameter precedence',()=>{const {buschSmartCardConfig}=ladeKarte(['buschSmartCardConfig']);assert.deepEqual(JSON.parse(JSON.stringify(buschSmartCardConfig({card_param:'cards',card:{type:'grid'}},[{type:'tile',entity:'light.a'}]))),{type:'grid',cards:[{type:'tile',entity:'light.a'}]});});
test('an obsolete target creation cannot overwrite a result that returned to the current configuration',async()=>{
 let release;const {BuschSmartEntities,buschCoreKey}=ladeKarte(['BuschSmartEntities','buschCoreKey'],{window:{customCards:[],loadCardHelpers:()=>new Promise(r=>release=r)},Event:class{}});
 const card=new BuschSmartEntities();card._generation=0;card._query={};card._config={card:{type:'entities'}};card._core={lastErrors:new Map()};card._hass={};card._child={marker:'original'};card._signature=buschCoreKey({type:'entities',entities:[{entity:'sensor.a'}]});card._debug=()=>{};card.dispatchEvent=()=>{};
 const pending=card._update([{entity:'sensor.b'}]);await card._update([{entity:'sensor.a'}]);release({createCardElement(){throw Error('obsolete target must not build');}});await pending;assert.equal(card._child.marker,'original');
});
test('editor nonstructural changes retain current configuration across form callbacks',()=>{
 const {BuschSmartEntitiesEditor}=ladeKarte(['BuschSmartEntitiesEditor'],{CustomEvent:class{constructor(type,options){Object.assign(this,options)}}});const editor=new BuschSmartEntitiesEditor();editor._config={filter:{include:[]}};editor.dispatchEvent=()=>{};let rendered=0;editor._render=()=>rendered++;const captured=editor._config;editor._emit({...captured,debug:true},false);editor._emit({...captured,show_empty:false},false);assert.equal(editor._config.debug,true);assert.equal(editor._config.show_empty,false);assert.equal(rendered,0);
});
test('a target card may mutate its own configuration without corrupting shared query rows',()=>{const {buschSmartCardConfig}=ladeKarte(['buschSmartCardConfig']);const rows=[{entity:'sensor.a',tap_action:{action:'more-info'}}];const target=buschSmartCardConfig({},rows);target.entities[0].tap_action.action='none';assert.equal(rows[0].tap_action.action,'more-info');});
