'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {ladeKarte}=require('./laden');const {baueHass}=require('./geraet-attrappe');
function setup(extra={}){const api=ladeKarte(['BuschCardsCore'],{performance,setTimeout,clearTimeout,...extra});const c=new api.BuschCardsCore(),h=baueHass();h.formatEntityState=s=>s?.state;c.hass=h;c.seed(h);return {c,h};}
const config={filter:{include:[{domain:'sensor',integration:'shelly',state:'< 20'}]}};
test('smart query shares results, ignores unrelated changes and evaluates one relevant entity',()=>{const {c,h}=setup();assert.equal(typeof c.smartQuery,'function');const q=c.smartQuery(config);assert.equal(q,c.smartQuery(config));let count=0;const off=c.subscribe(q,()=>count++);const n=q.metrics.evaluated;count=0;c.updateState('light.decke',{...h.states['light.decke'],state:'off'});assert.equal(q.metrics.evaluated,n);assert.equal(count,0);c.updateState('sensor.decke_leistung',{...h.states['sensor.decke_leistung'],state:'100'});assert.equal(q.metrics.evaluated,n+1);assert.equal(count,1);off();c.dispose();});
test('group membership changes refresh dependent smart queries',()=>{const {c}=setup();c.updateState('group.demo',{state:'on',attributes:{entity_id:['sensor.decke_leistung']}});const q=c.smartQuery({filter:{include:[{group:'group.demo'}]}});const off=c.subscribe(q,()=>{});assert.equal(q.result.length,1);c.updateState('group.demo',{state:'on',attributes:{entity_id:[]}});assert.equal(q.result.length,0);off();c.dispose();});
test('different value projections never share a final result cache',()=>{const {c}=setup();const a=c.smartQuery({...config,value:{type:'device_id'},unique_values:true}),b=c.smartQuery({...config,value:{type:'attribute',attribute:'friendly_name'}});assert.notEqual(a,b);assert.deepEqual([...a.result],['d1']);assert.ok(b.result.length>1);c.dispose();});
test('leave and reenter preserves original state order before pagination',()=>{const {c,h}=setup();const q=c.smartQuery({filter:{include:[{domain:'sensor',state:'< 20'}]},sort:{count:2}});const off=c.subscribe(q,()=>{});const before=JSON.stringify(q.result);c.updateState('sensor.decke_leistung',{...h.states['sensor.decke_leistung'],state:'100'});c.updateState('sensor.decke_leistung',{...h.states['sensor.decke_leistung'],state:'12.4'});assert.equal(JSON.stringify(q.result),before);off();c.dispose();});
test('invalid regex is isolated and does not stop another smart query',()=>{const {c,h}=setup();const invalid=c.smartQuery({filter:{include:[{entity_id:'/[bad/'}]}});assert.ok(invalid.error);const valid=c.smartQuery(config),off=c.subscribe(valid,()=>{});c.updateState('sensor.decke_leistung',{...h.states['sensor.decke_leistung'],state:'100'});assert.ok(!valid.result.some(e=>e.entity==='sensor.decke_leistung'));off();c.dispose();});
test('stringification patterns are not mistaken for literal index keys',()=>{const {c}=setup();const q=c.smartQuery({filter:{include:[{domain:'$$"sensor"'}]}});assert.ok(q.result.length>0);c.dispose();});
test('different target cards share the same declarative computation',()=>{const {c}=setup();assert.equal(c.smartQuery({...config,card:{type:'entities'}}),c.smartQuery({...config,card:{type:'glance'},debug:true}));c.dispose();});
test('template subscribers share a backend subscription and preserve errors until recovery',async()=>{
 const {c,h}=setup();let receive,calls=0,stopped=0;h.connection={subscribeMessage:async cb=>{calls++;receive=cb;return ()=>stopped++;}};
 const q=c.smartQuery({filter:{template:'{{ states.sensor | list }}'}});const off1=c.subscribe(q,()=>{}),off2=c.subscribe(q,()=>{});await Promise.resolve();await Promise.resolve();assert.equal(calls,1);
 receive({result:['sensor.decke_leistung']});await Promise.resolve();assert.equal(q.result.length,1);
 receive({error:'bad'});c.updateState('sensor.decke_leistung',{...h.states['sensor.decke_leistung'],state:'9'});assert.ok(q.error);
 receive({result:[]});await Promise.resolve();assert.equal(q.error,null);assert.equal(q.result.length,0);off1();assert.equal(stopped,0);off2();assert.equal(stopped,1);c.dispose();
});
test('synchronous template transport failures become visible query errors',async()=>{const {c,h}=setup();h.connection={subscribeMessage(){throw Error('offline');}};const q=c.smartQuery({filter:{template:'{{ states }}'}});const off=c.subscribe(q,()=>{});for(let i=0;i<8;i++)await Promise.resolve();assert.ok(q.error);off();c.dispose();});
test('numeric timestamp attributes schedule their next age boundary',()=>{const {c}=setup();c.updateState('sensor.time',{entity_id:'sensor.time',state:'on',attributes:{timestamp:Date.now()}});const q=c.smartQuery({filter:{include:[{entity_id:'sensor.time',attributes:{timestamp:'< 1 m ago'}}]}});assert.equal(q.result.length,1);assert.ok(Number.isFinite(q.nextDeadline));c.dispose();});
test('locale format changes invalidate translated state comparisons',()=>{const {c,h}=setup();h.formatEntityState=()=>h.locale.number_format||'before';c.attach(h);const q=c.smartQuery({filter:{include:[{state:'after'}]}});const off=c.subscribe(q,()=>{});assert.equal(q.result.length,0);h.locale={...h.locale,number_format:'after'};c.attach(h);assert.ok(q.result.length>0);off();c.dispose();});
test('shared object values cannot mutate HA state attributes',()=>{const {c}=setup();const object={nested:1};c.updateState('sensor.object',{entity_id:'sensor.object',state:'1',attributes:{object}});const q=c.smartQuery({filter:{include:[{entity_id:'sensor.object'}]},value:{type:'attribute',attribute:'object'}});assert.throws(()=>q.result[0].nested=2);assert.equal(object.nested,1);assert.equal(Object.isFrozen(object),false);c.dispose();});
