'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
function load(){
 const file=process.env.BUSCH_UNRAID_FRAGMENT || path.join(__dirname,'../dist/busch-cards.js');
 const source=fs.readFileSync(file,'utf8');
 const registered=new Map();
 class Element{constructor(tag='div'){this.tagName=tag;this.isConnected=false;this.childNodes=[];this.listeners={};this.attributes={};}attachShadow(){return this.shadowRoot=new Element();}replaceChildren(...nodes){this.childNodes=nodes;}appendChild(node){this.childNodes.push(node);return node;}get firstChild(){return this.childNodes[0];}addEventListener(type,fn){this.listeners[type]=fn;}setAttribute(key,value){this.attributes[key]=value;}dispatchEvent(e){this.event=e;}}
 const context={performance,setTimeout,clearTimeout,HTMLElement:Element,customElements:{define:(k,v)=>registered.set(k,v),get:k=>registered.get(k)},window:{customCards:[],confirm:()=>true},navigator:{language:'de'},console,CustomEvent:class {constructor(type,init){this.type=type;Object.assign(this,init);}},document:{createElement:tag=>new Element(tag)},buschTexte:(t,h)=>t[h?.locale?.language?.startsWith('de')?'de':'en'],buschSchemaMitTexten:s=>s};
 vm.createContext(context);
 vm.runInContext(source,context);
 return {...vm.runInContext('({buschMediaResolve:typeof buschMediaResolve==="undefined"?null:buschMediaResolve,buschMedia:typeof buschMedia==="undefined"?null:buschMedia,BuschUnraidVmCard:typeof BuschUnraidVmCard==="undefined"?null:BuschUnraidVmCard,BuschUnraidVmEditor:typeof BuschUnraidVmEditor==="undefined"?null:BuschUnraidVmEditor,buschUnraidModel,buschUnraidDevices,buschUnraidSchema,buschUiStatusSemantic,BUSCH_UNRAID_TEXT,BUSCH_UNRAID_DEFAULTS,BuschUnraidStackCard,BuschUnraidContainerCard,BuschUnraidStackEditor})',context),context,registered};
}
function fixture(){
 const core={devices:new Map(),entities:new Map(),getDeviceEntities(id){return [...this.entities.values()].filter(e=>e.device_id===id);}};
 core.devices.set('stack',{id:'stack',name:'Media',model:'Compose stack',config_entries:['instance']});
 core.devices.set('solo',{id:'solo',name:'Standalone',model:'Docker container',config_entries:['instance']});
 const add=(id,device,role,key,state='off',extra={})=>core.entities.set(id,{entity_id:id,device_id:device,platform:'unraid_ssh',config_entry_id:'instance',domain:id.split('.')[0],state,attributes:{kind:role.startsWith('stack')?'stack':'container',role:role.endsWith('restart')?'restart':role.endsWith('update')?'update':'control',config_entry_id:'instance',container_key:key,stack_key:device==='stack'?'media':null,container_name:key,...extra},registry:{}});
 add('switch.renamed','stack','container','web','on');
 add('switch.other','stack','container','db','off');
 add('switch.stack','stack','stack',null,'on');
 add('button.native','stack','container_restart','web','unknown');
 add('button.stack','stack','stack_restart',null,'unknown');
 add('update.correct','stack','container_update','web','on');
 add('update.wrong','stack','container_update','db','off');
 add('switch.solo','solo','container','solo','on');
 return {core,add};
}
test('both Unraid cards and editors register with HA discovery metadata',()=>{const l=load();for(const type of ['busch-unraid-stack-card','busch-unraid-container-card']){assert.ok(l.registered.has(type));assert.ok(l.registered.has(type+'-editor'));assert.ok(l.context.window.customCards.find(c=>c.type===type&&c.preview&&c.documentationURL));}});
test('Unraid cards let Sections size their dynamic content naturally',()=>{
 const l=load(),stack=new l.BuschUnraidStackCard(),container=new l.BuschUnraidContainerCard();
 for(const expanded of [false,true]){
  stack._expanded=expanded;
  assert.equal(Object.hasOwn(stack.getGridOptions(),'rows'),false);
  assert.equal(Object.hasOwn(stack.getGridOptions(),'min_rows'),false);
 }
 assert.equal(Object.hasOwn(container.getGridOptions(),'rows'),false);
 assert.equal(stack.getGridOptions().columns,12);
});
test('shared status roles preserve visible domain text',()=>{const semantic=load().buschUiStatusSemantic;for(const [raw,role] of [['running','success'],['online','success'],['partial','warning'],['failed','error'],['stopped','neutral'],['unavailable','unavailable'],['mystery','unknown']])assert.equal(semantic(raw),role);});
test('device scope requires unraid_ssh, correct model and chosen instance',()=>{const l=load(),{core}=fixture();core.devices.set('fake',{id:'fake',model:'Compose stack',config_entries:['instance']});assert.equal(l.buschUnraidDevices(core,'stack','instance').length,1);assert.equal(l.buschUnraidDevices(core,'stack','other').length,0);assert.equal(l.buschUnraidDevices(core,'container','instance').length,2);});
test('exact metadata associates renamed controls and matching update; stack partial state',()=>{const l=load(),{core}=fixture();const m=l.buschUnraidModel(core,{device_id:'stack'},'stack');assert.equal(m.containers.length,2);assert.equal(m.status,'partial');assert.equal(m.running,1);assert.equal(m.switch.entity_id,'switch.stack');const web=m.containers.find(c=>c.key==='web');assert.equal(web.restart.entity_id,'button.native');assert.equal(web.update.entity_id,'update.correct');});
test('container selector supports standalone and compose without entity-name parsing',()=>{const l=load(),{core}=fixture();assert.equal(l.buschUnraidModel(core,{device_id:'solo'},'container').selected.key,'solo');assert.equal(l.buschUnraidModel(core,{device_id:'stack',container_key:'db'},'container').selected.switch.entity_id,'switch.other');assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'container').selected,null);});
test('missing role metadata never fabricates restart or stack control',()=>{const l=load(),{core}=fixture();for(const e of core.entities.values()) e.attributes={};const m=l.buschUnraidModel(core,{device_id:'stack'},'stack');assert.equal(m.switch,null);assert.equal(m.restart,null);assert.equal(m.containers.length,0);});
test('defaults confirm destructive actions and every editor field has bilingual label/helper',()=>{const l=load(),{core}=fixture();assert.equal(l.BUSCH_UNRAID_DEFAULTS.confirm_stop,true);assert.equal(l.BUSCH_UNRAID_DEFAULTS.confirm_restart,true);for(const kind of ['stack','container'])for(const field of l.buschUnraidSchema(core,{device_id:'stack'},kind)){for(const lang of ['de','en']){assert.ok(l.BUSCH_UNRAID_TEXT[lang].labels[field.name],field.name);assert.ok(l.BUSCH_UNRAID_TEXT[lang].helpers[field.name],field.name);}}});
test('actions call real switch and native restart only, rejected confirmation sends nothing',async()=>{const l=load(),calls=[],card=new l.BuschUnraidStackCard();card._render=()=>{};card._config={...l.BUSCH_UNRAID_DEFAULTS};card._hass={locale:{language:'en'},callService:async(...args)=>calls.push(args)};const row={name:'Example',switch:{entity_id:'switch.actual',state:'on'},restart:{entity_id:'button.real',state:'unknown'}};l.context.window.confirm=()=>false;await card._action('stop',row);assert.equal(calls.length,0);l.context.window.confirm=()=>true;await card._action('restart',row);assert.equal(calls[0][0],'button');assert.equal(calls[0][1],'press');await card._action('start',row);assert.equal(calls[1][1],'turn_on');await card._action('restart',{...row,restart:null});assert.equal(calls.length,2);});
test('unavailable controls and repeated clicks cannot dispatch services',async()=>{const l=load(),card=new l.BuschUnraidStackCard(),calls=[];card._render=()=>{};card._config={...l.BUSCH_UNRAID_DEFAULTS};card._hass={callService:async(...args)=>calls.push(args)};await card._action('start',{switch:{entity_id:'switch.offline',state:'unavailable'}});assert.equal(calls.length,0);card._busy=true;await card._action('start',{switch:{entity_id:'switch.online',state:'off'}});assert.equal(calls.length,0);});

test('editor preserves device while changing a default field and clears dependents on actual instance change',()=>{const l=load(),{core}=fixture(),editor=new l.BuschUnraidStackEditor();editor._core=core;editor._hass={locale:{language:'en'}};editor.setConfig({device_id:'stack'});const event=value=>({detail:{value},stopPropagation(){}});editor._form.listeners['value-changed'](event({...editor._form.data,title:'Custom'}));assert.equal(editor.event.detail.config.device_id,'stack');editor._form.listeners['value-changed'](event({...editor._form.data,config_entry_id:'other'}));assert.equal(editor.event.detail.config.device_id,undefined);});
test('Unraid editor keeps form and prior configuration stable across rapid changes',()=>{const l=load(),{core}=fixture(),editor=new l.BuschUnraidStackEditor();editor._core=core;editor._hass={locale:{language:'en'}};const incoming={device_id:'stack',title:'Original'};editor.setConfig(incoming);const form=editor._form,previous=editor._config;const change=value=>form.listeners['value-changed']({detail:{value},stopPropagation(){}});change({title:'Edited'});change({show_status:false});assert.equal(editor.event.detail.config.title,'Edited');assert.equal(editor.event.detail.config.show_status,false);assert.equal(previous.title,'Original');assert.equal(incoming.title,'Original');assert.equal(editor._form,form);const saved=JSON.parse(JSON.stringify(editor.event.detail.config));editor.event.detail.config.title='external';assert.equal(editor._config.title,'Edited');editor.setConfig(saved);assert.equal(editor._form,form);let stopped=false;editor.listeners.keydown({stopPropagation(){stopped=true;}});assert.equal(stopped,true);});
test('render uses text nodes, filters stopped rows, and collapse removes rows',()=>{const l=load(),{core}=fixture(),card=new l.BuschUnraidStackCard();card._core=core;card._hass={locale:{language:'en'}};core.entities.get('switch.other').attributes.container_name='<img onerror=bad>';card.setConfig({device_id:'stack',state_filter:'stopped'});const all=node=>[node,...node.childNodes.flatMap(all)];let nodes=all(card.shadowRoot);assert.ok(nodes.some(n=>n.textContent==='<img onerror=bad>'));assert.ok(!nodes.some(n=>n.textContent==='web'));const toggle=nodes.find(n=>n.attributes['aria-expanded']==='true');toggle.listeners.click();nodes=all(card.shadowRoot);assert.ok(!nodes.some(n=>n.textContent==='<img onerror=bad>'));});
test('update opens only the matched entity details, without service installation',async()=>{const l=load(),card=new l.BuschUnraidContainerCard();card._hass={};await card._action('update',{update:{entity_id:'update.match'}});assert.equal(card.event.type,'hass-more-info');assert.equal(card.event.detail.entityId,'update.match');});
test('registry subscriptions and retain handles release on disconnect',()=>{const l=load(),{core}=fixture();let retains=0,releases=0,watches=0,unwatches=0;Object.assign(core,{attach(){},retain(){retains++;return()=>releases++;},watch(){watches++;return()=>unwatches++;}});l.context.ensureBuschCore=()=>core;const card=new l.BuschUnraidStackCard();card.isConnected=true;card.hass={};card.hass={};assert.equal(retains,1);assert.equal(watches,1);card.disconnectedCallback();assert.equal(releases,1);assert.equal(unwatches,1);card.connectedCallback();assert.equal(retains,2);});
test('missing native restart disables editor field with translated explanation and no action',()=>{const l=load(),{core}=fixture();core.entities.delete('button.native');core.entities.delete('button.stack');for(const language of ['de','en']){const schema=l.buschUnraidSchema(core,{device_id:'stack'},'stack');assert.equal(schema.find(s=>s.name==='show_restart').disabled,true);const editor=new l.BuschUnraidStackEditor();editor._core=core;editor._hass={locale:{language}};editor.setConfig({device_id:'stack'});assert.equal(editor._form.computeHelper(schema.find(s=>s.name==='show_restart')),l.BUSCH_UNRAID_TEXT[language].restart_missing);}});
test('unknown or unavailable containers are not reported as a stopped stack',()=>{const l=load(),{core}=fixture();core.entities.get('switch.renamed').state='unavailable';core.entities.get('switch.other').state='unavailable';assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'stack').status,'unavailable');});
test('legacy registry unique IDs join controls and updates without interpreting entity IDs',()=>{const l=load(),{core}=fixture();core.entities.clear();for(const [id,unique_id] of [['switch.renamed','instance_container_web'],['update.whatever','instance_update_web'],['switch.master','instance_stack_media'],['button.check','instance_check_updates']])core.entities.set(id,{entity_id:id,domain:id.split('.')[0],device_id:'stack',platform:'unraid_ssh',config_entry_id:'instance',state:'on',attributes:{friendly_name:id},registry:{unique_id}});const m=l.buschUnraidModel(core,{device_id:'stack'},'stack');assert.equal(m.containers.length,1);assert.equal(m.switch.entity_id,'switch.master');assert.equal(m.containers[0].update.entity_id,'update.whatever');assert.equal(m.restart,null);assert.equal(m.containers[0].restart,null);});
test('legacy prefixes from other instances and platforms cannot match',()=>{const l=load(),{core}=fixture();core.entities.clear();for(const [id,platform,entry,uid] of [['switch.bad','unraid_ssh','instance','other_container_web'],['switch.fake','mqtt','instance','instance_container_web']])core.entities.set(id,{entity_id:id,domain:'switch',device_id:'stack',platform,config_entry_id:entry,state:'on',attributes:{},registry:{unique_id:uid}});assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'stack').containers.length,0);});
test('unchanged visible data preserves DOM nodes while relevant changes rebuild',()=>{const l=load(),{core}=fixture(),card=new l.BuschUnraidStackCard();card._core=core;card._hass={locale:{language:'en'}};card.setConfig({device_id:'stack'});const before=card.shadowRoot.childNodes[1];card._render();assert.equal(card.shadowRoot.childNodes[1],before);core.entities.get('switch.renamed').state='off';card._render();assert.notEqual(card.shadowRoot.childNodes[1],before);});
test('stack editor does not offer an unused stack update override',()=>{const l=load(),{core}=fixture();assert.ok(!l.buschUnraidSchema(core,{device_id:'stack'},'stack').some(f=>f.name==='update_entity'));assert.ok(l.buschUnraidSchema(core,{device_id:'stack'},'container').some(f=>f.name==='update_entity'));});
test('legacy Compose container retains its stack association',()=>{const l=load(),{core}=fixture();core.entities.clear();core.entities.set('switch.renamed',{entity_id:'switch.renamed',domain:'switch',device_id:'stack',platform:'unraid_ssh',config_entry_id:'instance',state:'on',attributes:{},registry:{unique_id:'instance_container_web'}});assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'container').selected.stack,'Media');});
test('mixed rollout matches a legacy update to the new control by exact documented Docker name',()=>{const l=load(),{core}=fixture();const update=core.entities.get('update.correct');update.attributes={};update.registry.unique_id='instance_update_web';const web=l.buschUnraidModel(core,{device_id:'stack'},'stack').containers.find(c=>c.key==='web');assert.equal(web.update.entity_id,'update.correct');});
test('explicit update selection applies to the selected container and stays within its device',()=>{const l=load(),{core}=fixture();const config={device_id:'stack',container_key:'web',update_entity:'update.wrong'};assert.equal(l.buschUnraidModel(core,config,'container').selected.update.entity_id,'update.wrong');core.entities.get('update.wrong').device_id='solo';assert.equal(l.buschUnraidModel(core,config,'container').selected.update,null);});
test('real Core stream updates refresh a visible Unraid card without a hass setter',async()=>{
 const l=load(),core=vm.runInContext('new BuschCardsCore()',l.context),{core:sample}=fixture();
 const entities={},states={};for(const info of sample.entities.values()){entities[info.entity_id]={entity_id:info.entity_id,device_id:info.device_id,platform:info.platform,config_entry_id:info.config_entry_id};states[info.entity_id]={entity_id:info.entity_id,state:info.state,attributes:info.attributes};}
 const hass={entities,states,devices:Object.fromEntries(sample.devices),areas:{},locale:{language:'en'}};core.seed(hass);
 const card=new l.BuschUnraidStackCard();card.isConnected=true;card._core=core;card._hass=hass;card.setConfig({device_id:'stack'});const before=card.shadowRoot.childNodes[1];
 core.updateState('switch.renamed',{...states['switch.renamed'],state:'off'});await Promise.resolve();assert.notEqual(card.shadowRoot.childNodes[1],before);assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'stack').running,0);card.disconnectedCallback();core.dispose();
});
test('a pending service completion after disconnect does not restore device subscriptions',async()=>{
 const l=load(),{core}=fixture();let listeners=0,resolve;core.watchDevice=()=>{listeners++;return ()=>listeners--;};
 const card=new l.BuschUnraidStackCard();card.isConnected=true;card._core=core;card._hass={locale:{language:'en'},callService:()=>new Promise(r=>resolve=r)};card.setConfig({device_id:'stack',confirm_stop:false});assert.equal(listeners,1);
 const action=card._action('stop',l.buschUnraidModel(core,card._config,'stack'));card.isConnected=false;card.disconnectedCallback();assert.equal(listeners,0);resolve();await action;assert.equal(listeners,0);
});

function vmFixture(){const {core}=fixture();core.devices.set('vm',{id:'vm',name:'Guest',model:'Virtual machine',config_entries:['instance']});const put=(role,state,extra={})=>{const domain=role==='control'?'switch':role==='restart'?'button':'sensor',id=domain+'.arbitrary_'+role;core.entities.set(id,{entity_id:id,domain,device_id:'vm',config_entry_id:'instance',platform:'unraid_ssh',state,registry:{},attributes:{kind:'vm',role,config_entry_id:'instance',vm_key:'Guest',vm_name:'Guest',vm_state:'running',...extra}});return id;};put('control','on');put('restart','unknown');put('cpu','250');put('ram_allocated',String(8*1024**3));put('ram_max',String(16*1024**3));put('ram_host_rss',String(9*1024**3));return {core,put};}
test('VM devices and metadata join exactly in instance scope; invalid device does not auto-select',()=>{const l=load(),{core}=vmFixture();assert.ok(l.registered.has('busch-unraid-vm-card'));const m=l.buschUnraidModel(core,{device_id:'vm',config_entry_id:'instance'},'vm');assert.equal(m.selected.name,'Guest');assert.equal(m.selected.cpu,250);assert.equal(m.selected.ram_label,'ram_allocated');assert.equal(m.selected.ram,8*1024**3);assert.equal(m.selected.ram_total,16*1024**3);assert.equal(m.selected.ip,undefined);assert.equal(l.buschUnraidModel(core,{device_id:'bad'},'vm').selected,null);assert.equal(l.buschUnraidModel(core,{device_id:'vm',config_entry_id:'other'},'vm').selected,null);});
test('guest used RAM beats allocation but never substitutes host RSS; stopped metrics unavailable',()=>{const l=load(),{core,put}=vmFixture();put('ram_used','0');let row=l.buschUnraidModel(core,{device_id:'vm'},'vm').selected;assert.ok(row);assert.equal(row.ram,0);assert.equal(row.ram_label,'ram_used');assert.equal(row.ram_total,8*1024**3);put('ram_used','unavailable');put('ram_allocated','unavailable');row=l.buschUnraidModel(core,{device_id:'vm'},'vm').selected;assert.equal(row.ram,null);assert.equal(row.cpu,250);core.entities.get('switch.arbitrary_control').state='off';row=l.buschUnraidModel(core,{device_id:'vm'},'vm').selected;assert.equal(row.cpu,null);});
test('container metrics are scoped and stack aggregates only complete running members without invented budget',()=>{const l=load(),{core}=fixture();const metric=(role,state,key='web',entry='instance')=>{const id='sensor.'+role+key+entry;core.entities.set(id,{entity_id:id,domain:'sensor',device_id:'stack',platform:'unraid_ssh',config_entry_id:entry,state,registry:{},attributes:{kind:'container',role,container_key:key,config_entry_id:entry}});};metric('cpu','150');metric('ram_used','4096');metric('ram_limit','8192');metric('cpu','900','web','other');let m=l.buschUnraidModel(core,{device_id:'stack'},'stack');assert.equal(m.containers.find(c=>c.key==='web').cpu,150);assert.equal(m.cpu,150);assert.equal(m.ram,4096);assert.equal(m.ram_total,null);metric('cpu','unavailable');m=l.buschUnraidModel(core,{device_id:'stack'},'stack');assert.equal(m.cpu,null);});
test('shared media honors auto priority and never treats Docker image tag as a picture',()=>{const l=load();assert.equal(typeof l.buschMediaResolve,'function');assert.equal(l.buschMediaResolve({image:'custom.png',icon:'mdi:star'},{entity_picture:'entity.png',image:'docker:tag'},'mdi:server').image,'entity.png');assert.equal(l.buschMediaResolve({display_mode:'image',image:'custom.png'},{entity_picture:'entity.png'},'mdi:server').image,'custom.png');assert.equal(l.buschMediaResolve({display_mode:'icon',image:'custom.png',icon:'mdi:star'},{},'mdi:server').image,null);assert.equal(l.buschMediaResolve({}, {image:'docker:tag'},'mdi:server').image,null);const node=l.buschMedia({}, {entity_picture:'bad.png'},'mdi:server','card-icon');node.childNodes[0].listeners.error();assert.equal(node.childNodes[0].tagName,'ha-icon');});
test('VM editor exposes all required fields and persists explicit false and empty image across setConfig',()=>{const l=load(),{core}=vmFixture();assert.equal(typeof l.BuschUnraidVmEditor,'function');const editor=new l.BuschUnraidVmEditor();editor._core=core;editor._hass={locale:{language:'de'}};editor.setConfig({device_id:'vm'});const names=editor._form.schema.map(f=>f.name);for(const name of ['device_id','display_mode','image','icon','show_cpu','show_ram','show_uptime','show_ip','show_disk','debug'])assert.ok(names.includes(name),name);for(const field of editor._form.schema)for(const lang of ['de','en']){assert.ok(l.BUSCH_UNRAID_TEXT[lang].labels[field.name]);assert.ok(l.BUSCH_UNRAID_TEXT[lang].helpers[field.name]);}editor._form.listeners['value-changed']({detail:{value:{show_cpu:false,image:'',confirm_restart:false}},stopPropagation(){}});const saved=JSON.parse(JSON.stringify(editor.event.detail.config));editor.setConfig(saved);assert.equal(editor._form.data.show_cpu,false);assert.equal(editor._form.data.image,'');assert.equal(editor._form.data.confirm_restart,false);});
test('VM actions confirm stop/restart, surface error and suppress repeat clicks',async()=>{const l=load(),{core}=vmFixture();assert.equal(typeof l.BuschUnraidVmCard,'function');const card=new l.BuschUnraidVmCard(),calls=[];card._render=()=>{};card._config={...l.BUSCH_UNRAID_DEFAULTS};card._hass={callService:async(...args)=>{calls.push(args);throw Error('rejected')}};const row=l.buschUnraidModel(core,{device_id:'vm'},'vm').selected;l.context.window.confirm=()=>false;await card._action('stop',row);assert.equal(calls.length,0);l.context.window.confirm=()=>true;await card._action('restart',row);assert.equal(calls[0][0],'button');assert.ok(card._error);assert.equal(card._busy,false);await card._action('details',row);assert.equal(card.event.detail.entityId,'switch.arbitrary_control');card._busy=true;await card._action('start',row);assert.equal(calls.length,1);});
test('VM raw libvirt states remain explicit and unsafe lifecycle actions are suppressed',async()=>{const l=load(),{core,put}=vmFixture(),card=new l.BuschUnraidVmCard(),calls=[];card._render=()=>{};card._config={...l.BUSCH_UNRAID_DEFAULTS,confirm_restart:false,confirm_stop:false};card._hass={callService:async(...args)=>calls.push(args)};for(const [raw,expected] of [['paused','paused'],['blocked','blocked'],['in shutdown','stopping'],['crashed','failed'],['pmsuspended','suspended']]){put('state',raw);let row=l.buschUnraidModel(core,{device_id:'vm'},'vm').selected;assert.equal(row.status,expected);await card._action('start',row);await card._action('restart',row);}assert.equal(calls.length,0);});
test('backend canonical VM enum recognizes shut_off, in_shutdown and idle',()=>{const l=load(),{core,put}=vmFixture();for(const [state,want] of [['shut_off','stopped'],['in_shutdown','stopping'],['idle','idle']]){put('state',state);assert.equal(l.buschUnraidModel(core,{device_id:'vm'},'vm').selected.status,want);}});
test('same container identity in two instances cannot resolve ambiguously without explicit scope',()=>{const l=load(),{core}=fixture();const other={...core.entities.get('switch.renamed'),entity_id:'switch.second',config_entry_id:'other',attributes:{...core.entities.get('switch.renamed').attributes,config_entry_id:'other'}};core.entities.set(other.entity_id,other);assert.equal(l.buschUnraidModel(core,{device_id:'stack',container_key:'web'},'container').selected,null);assert.equal(l.buschUnraidModel(core,{device_id:'stack',container_key:'web',config_entry_id:'instance'},'container').selected.switch.entity_id,'switch.renamed');});
test('crashed VM renders concise error status instead of an action-error message',()=>{const l=load(),{core,put}=vmFixture(),card=new l.BuschUnraidVmCard();put('state','crashed');card._core=core;card._hass={locale:{language:'de'}};card.setConfig({device_id:'vm'});const all=n=>[n,...n.childNodes.flatMap(all)];assert.ok(all(card.shadowRoot).some(n=>n.className==='status-badge status-error'&&n.textContent==='Fehler'));});
