'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
function load(){
 const file=process.env.BUSCH_UNRAID_FRAGMENT || path.join(__dirname,'../dist/busch-cards.js');
 const source=fs.readFileSync(file,'utf8');
 const registered=new Map();
 class Element{constructor(tag='div'){this.tagName=tag;this.isConnected=false;this.childNodes=[];this.listeners={};this.attributes={};}attachShadow(){return this.shadowRoot=new Element();}replaceChildren(...nodes){this.childNodes=nodes;}appendChild(node){this.childNodes.push(node);return node;}get firstChild(){return this.childNodes[0];}addEventListener(type,fn){this.listeners[type]=fn;}setAttribute(key,value){this.attributes[key]=value;}dispatchEvent(e){this.event=e;}}
 const context={performance,setTimeout,clearTimeout,HTMLElement:Element,customElements:{define:(k,v)=>registered.set(k,v),get:k=>registered.get(k)},window:{customCards:[],confirm:()=>true},navigator:{language:'de'},console,CustomEvent:class {constructor(type,init){this.type=type;Object.assign(this,init);}},document:{createElement:tag=>new Element(tag)},buschTexte:(t,h)=>t[h?.locale?.language?.startsWith('de')?'de':'en'],buschSchemaMitTexten:s=>s};
 vm.createContext(context);
 vm.runInContext(source,context);
 return {...vm.runInContext('({buschUnraidModel,buschUnraidDevices,buschUnraidSchema,BUSCH_UNRAID_TEXT,BUSCH_UNRAID_DEFAULTS,BuschUnraidStackCard,BuschUnraidContainerCard,BuschUnraidStackEditor})',context),context,registered};
}
function fixture(){
 const core={devices:new Map(),entities:new Map(),getDeviceEntities(id){return [...this.entities.values()].filter(e=>e.device_id===id);}};
 core.devices.set('stack',{id:'stack',name:'Media',model:'Compose stack',config_entries:['instance']});
 core.devices.set('solo',{id:'solo',name:'Standalone',model:'Docker container',config_entries:['instance']});
 const add=(id,device,role,key,state='off',extra={})=>core.entities.set(id,{entity_id:id,device_id:device,platform:'unraid_ssh',config_entry_id:'instance',domain:id.split('.')[0],state,attributes:{kind:role.startsWith('stack')?'stack':'container',role:role.endsWith('restart')?'restart':role.endsWith('update')?'update':'control',config_entry_id:'instance',container_key:key,stack_key:device==='stack'?'media':null,container_name:key,...extra},registry:{}});
 add('switch.renamed','stack','container','web','on');
 add('switch.other','stack','container','db','off');
 add('switch.stack','stack','stack',null,'on');
 add('button.native','stack','container_restart','web','unknown');
 add('button.stack','stack','stack_restart',null,'unknown');
 add('update.correct','stack','container_update','web','on');
 add('update.wrong','stack','container_update','db','off');
 add('switch.solo','solo','container','solo','on');
 return {core,add};
}
test('both Unraid cards and editors register with HA discovery metadata',()=>{const l=load();for(const type of ['busch-unraid-stack-card','busch-unraid-container-card']){assert.ok(l.registered.has(type));assert.ok(l.registered.has(type+'-editor'));assert.ok(l.context.window.customCards.find(c=>c.type===type&&c.preview&&c.documentationURL));}});
test('device scope requires unraid_ssh, correct model and chosen instance',()=>{const l=load(),{core}=fixture();core.devices.set('fake',{id:'fake',model:'Compose stack',config_entries:['instance']});assert.equal(l.buschUnraidDevices(core,'stack','instance').length,1);assert.equal(l.buschUnraidDevices(core,'stack','other').length,0);assert.equal(l.buschUnraidDevices(core,'container','instance').length,2);});
test('exact metadata associates renamed controls and matching update; stack partial state',()=>{const l=load(),{core}=fixture();const m=l.buschUnraidModel(core,{device_id:'stack'},'stack');assert.equal(m.containers.length,2);assert.equal(m.status,'partial');assert.equal(m.running,1);assert.equal(m.switch.entity_id,'switch.stack');const web=m.containers.find(c=>c.key==='web');assert.equal(web.restart.entity_id,'button.native');assert.equal(web.update.entity_id,'update.correct');});
test('container selector supports standalone and compose without entity-name parsing',()=>{const l=load(),{core}=fixture();assert.equal(l.buschUnraidModel(core,{device_id:'solo'},'container').selected.key,'solo');assert.equal(l.buschUnraidModel(core,{device_id:'stack',container_key:'db'},'container').selected.switch.entity_id,'switch.other');assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'container').selected,null);});
test('missing role metadata never fabricates restart or stack control',()=>{const l=load(),{core}=fixture();for(const e of core.entities.values()) e.attributes={};const m=l.buschUnraidModel(core,{device_id:'stack'},'stack');assert.equal(m.switch,null);assert.equal(m.restart,null);assert.equal(m.containers.length,0);});
test('defaults confirm destructive actions and every editor field has bilingual label/helper',()=>{const l=load(),{core}=fixture();assert.equal(l.BUSCH_UNRAID_DEFAULTS.confirm_stop,true);assert.equal(l.BUSCH_UNRAID_DEFAULTS.confirm_restart,true);for(const kind of ['stack','container'])for(const field of l.buschUnraidSchema(core,{device_id:'stack'},kind)){for(const lang of ['de','en']){assert.ok(l.BUSCH_UNRAID_TEXT[lang].labels[field.name],field.name);assert.ok(l.BUSCH_UNRAID_TEXT[lang].helpers[field.name],field.name);}}});
test('actions call real switch and native restart only, rejected confirmation sends nothing',async()=>{const l=load(),calls=[],card=new l.BuschUnraidStackCard();card._render=()=>{};card._config={...l.BUSCH_UNRAID_DEFAULTS};card._hass={locale:{language:'en'},callService:async(...args)=>calls.push(args)};const row={name:'Example',switch:{entity_id:'switch.actual',state:'on'},restart:{entity_id:'button.real',state:'unknown'}};l.context.window.confirm=()=>false;await card._action('stop',row);assert.equal(calls.length,0);l.context.window.confirm=()=>true;await card._action('restart',row);assert.equal(calls[0][0],'button');assert.equal(calls[0][1],'press');await card._action('start',row);assert.equal(calls[1][1],'turn_on');await card._action('restart',{...row,restart:null});assert.equal(calls.length,2);});
test('unavailable controls and repeated clicks cannot dispatch services',async()=>{const l=load(),card=new l.BuschUnraidStackCard(),calls=[];card._render=()=>{};card._config={...l.BUSCH_UNRAID_DEFAULTS};card._hass={callService:async(...args)=>calls.push(args)};await card._action('start',{switch:{entity_id:'switch.offline',state:'unavailable'}});assert.equal(calls.length,0);card._busy=true;await card._action('start',{switch:{entity_id:'switch.online',state:'off'}});assert.equal(calls.length,0);});

test('editor preserves device while changing a default field and clears dependents on actual instance change',()=>{const l=load(),{core}=fixture(),editor=new l.BuschUnraidStackEditor();editor._core=core;editor._hass={locale:{language:'en'}};editor.setConfig({device_id:'stack'});const event=value=>({detail:{value},stopPropagation(){}});editor._form.listeners['value-changed'](event({...editor._form.data,title:'Custom'}));assert.equal(editor.event.detail.config.device_id,'stack');editor._form.listeners['value-changed'](event({...editor._form.data,config_entry_id:'other'}));assert.equal(editor.event.detail.config.device_id,undefined);});
test('render uses text nodes, filters stopped rows, and collapse removes rows',()=>{const l=load(),{core}=fixture(),card=new l.BuschUnraidStackCard();card._core=core;card._hass={locale:{language:'en'}};core.entities.get('switch.other').attributes.container_name='<img onerror=bad>';card.setConfig({device_id:'stack',state_filter:'stopped'});const all=node=>[node,...node.childNodes.flatMap(all)];let nodes=all(card.shadowRoot);assert.ok(nodes.some(n=>n.textContent==='<img onerror=bad>'));assert.ok(!nodes.some(n=>n.textContent==='web'));const toggle=nodes.find(n=>n.attributes['aria-expanded']==='true');toggle.listeners.click();nodes=all(card.shadowRoot);assert.ok(!nodes.some(n=>n.textContent==='<img onerror=bad>'));});
test('update opens only the matched entity details, without service installation',async()=>{const l=load(),card=new l.BuschUnraidContainerCard();card._hass={};await card._action('update',{update:{entity_id:'update.match'}});assert.equal(card.event.type,'hass-more-info');assert.equal(card.event.detail.entityId,'update.match');});
test('registry subscriptions and retain handles release on disconnect',()=>{const l=load(),{core}=fixture();let retains=0,releases=0,watches=0,unwatches=0;Object.assign(core,{attach(){},retain(){retains++;return()=>releases++;},watch(){watches++;return()=>unwatches++;}});l.context.ensureBuschCore=()=>core;const card=new l.BuschUnraidStackCard();card.isConnected=true;card.hass={};card.hass={};assert.equal(retains,1);assert.equal(watches,1);card.disconnectedCallback();assert.equal(releases,1);assert.equal(unwatches,1);card.connectedCallback();assert.equal(retains,2);});
test('missing native restart disables editor field with translated explanation and no action',()=>{const l=load(),{core}=fixture();core.entities.delete('button.native');core.entities.delete('button.stack');for(const language of ['de','en']){const schema=l.buschUnraidSchema(core,{device_id:'stack'},'stack');assert.equal(schema.find(s=>s.name==='show_restart').disabled,true);const editor=new l.BuschUnraidStackEditor();editor._core=core;editor._hass={locale:{language}};editor.setConfig({device_id:'stack'});assert.equal(editor._form.computeHelper(schema.find(s=>s.name==='show_restart')),l.BUSCH_UNRAID_TEXT[language].restart_missing);}});
test('unknown or unavailable containers are not reported as a stopped stack',()=>{const l=load(),{core}=fixture();core.entities.get('switch.renamed').state='unavailable';core.entities.get('switch.other').state='unavailable';assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'stack').status,'unavailable');});
test('legacy registry unique IDs join controls and updates without interpreting entity IDs',()=>{const l=load(),{core}=fixture();core.entities.clear();for(const [id,unique_id] of [['switch.renamed','instance_container_web'],['update.whatever','instance_update_web'],['switch.master','instance_stack_media'],['button.check','instance_check_updates']])core.entities.set(id,{entity_id:id,domain:id.split('.')[0],device_id:'stack',platform:'unraid_ssh',config_entry_id:'instance',state:'on',attributes:{friendly_name:id},registry:{unique_id}});const m=l.buschUnraidModel(core,{device_id:'stack'},'stack');assert.equal(m.containers.length,1);assert.equal(m.switch.entity_id,'switch.master');assert.equal(m.containers[0].update.entity_id,'update.whatever');assert.equal(m.restart,null);assert.equal(m.containers[0].restart,null);});
test('legacy prefixes from other instances and platforms cannot match',()=>{const l=load(),{core}=fixture();core.entities.clear();for(const [id,platform,entry,uid] of [['switch.bad','unraid_ssh','instance','other_container_web'],['switch.fake','mqtt','instance','instance_container_web']])core.entities.set(id,{entity_id:id,domain:'switch',device_id:'stack',platform,config_entry_id:entry,state:'on',attributes:{},registry:{unique_id:uid}});assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'stack').containers.length,0);});
test('unchanged visible data preserves DOM nodes while relevant changes rebuild',()=>{const l=load(),{core}=fixture(),card=new l.BuschUnraidStackCard();card._core=core;card._hass={locale:{language:'en'}};card.setConfig({device_id:'stack'});const before=card.shadowRoot.childNodes[1];card._render();assert.equal(card.shadowRoot.childNodes[1],before);core.entities.get('switch.renamed').state='off';card._render();assert.notEqual(card.shadowRoot.childNodes[1],before);});
test('stack editor does not offer an unused stack update override',()=>{const l=load(),{core}=fixture();assert.ok(!l.buschUnraidSchema(core,{device_id:'stack'},'stack').some(f=>f.name==='update_entity'));assert.ok(l.buschUnraidSchema(core,{device_id:'stack'},'container').some(f=>f.name==='update_entity'));});
test('legacy Compose container retains its stack association',()=>{const l=load(),{core}=fixture();core.entities.clear();core.entities.set('switch.renamed',{entity_id:'switch.renamed',domain:'switch',device_id:'stack',platform:'unraid_ssh',config_entry_id:'instance',state:'on',attributes:{},registry:{unique_id:'instance_container_web'}});assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'container').selected.stack,'Media');});
test('mixed rollout matches a legacy update to the new control by exact documented Docker name',()=>{const l=load(),{core}=fixture();const update=core.entities.get('update.correct');update.attributes={};update.registry.unique_id='instance_update_web';const web=l.buschUnraidModel(core,{device_id:'stack'},'stack').containers.find(c=>c.key==='web');assert.equal(web.update.entity_id,'update.correct');});
test('explicit update selection applies to the selected container and stays within its device',()=>{const l=load(),{core}=fixture();const config={device_id:'stack',container_key:'web',update_entity:'update.wrong'};assert.equal(l.buschUnraidModel(core,config,'container').selected.update.entity_id,'update.wrong');core.entities.get('update.wrong').device_id='solo';assert.equal(l.buschUnraidModel(core,config,'container').selected.update,null);});
test('real Core stream updates refresh a visible Unraid card without a hass setter',async()=>{
 const l=load(),core=vm.runInContext('new BuschCardsCore()',l.context),{core:sample}=fixture();
 const entities={},states={};for(const info of sample.entities.values()){entities[info.entity_id]={entity_id:info.entity_id,device_id:info.device_id,platform:info.platform,config_entry_id:info.config_entry_id};states[info.entity_id]={entity_id:info.entity_id,state:info.state,attributes:info.attributes};}
 const hass={entities,states,devices:Object.fromEntries(sample.devices),areas:{},locale:{language:'en'}};core.seed(hass);
 const card=new l.BuschUnraidStackCard();card.isConnected=true;card._core=core;card._hass=hass;card.setConfig({device_id:'stack'});const before=card.shadowRoot.childNodes[1];
 core.updateState('switch.renamed',{...states['switch.renamed'],state:'off'});await Promise.resolve();assert.notEqual(card.shadowRoot.childNodes[1],before);assert.equal(l.buschUnraidModel(core,{device_id:'stack'},'stack').running,0);card.disconnectedCallback();core.dispose();
});
test('a pending service completion after disconnect does not restore device subscriptions',async()=>{
 const l=load(),{core}=fixture();let listeners=0,resolve;core.watchDevice=()=>{listeners++;return ()=>listeners--;};
 const card=new l.BuschUnraidStackCard();card.isConnected=true;card._core=core;card._hass={locale:{language:'en'},callService:()=>new Promise(r=>resolve=r)};card.setConfig({device_id:'stack',confirm_stop:false});assert.equal(listeners,1);
 const action=card._action('stop',l.buschUnraidModel(core,card._config,'stack'));card.isConnected=false;card.disconnectedCallback();assert.equal(listeners,0);resolve();await action;assert.equal(listeners,0);
});
