"""Native HA form and Tile with offscreen synthetic states and mocked services.
No dashboard writes, real service calls, or credentials in reports.
"""
import json,pathlib,sys,re
from playwright.sync_api import sync_playwright
private=json.loads(pathlib.Path(sys.argv[2]).read_text());base=private['base_url'].rstrip('/')
auth={'hassUrl':base,'clientId':base+'/','expires':4102444800000,'expires_in':315360000,'refresh_token':'','access_token':private['token']}
source=pathlib.Path(sys.argv[1]).read_text().replace('busch-','task3-busch-').replace('ensureBuschCore(1)','window.__task3Core')
with sync_playwright() as pw:
 b=pw.chromium.launch();context=b.new_context(ignore_https_errors=True,viewport={'width':1000,'height':1200});context.add_init_script('localStorage.setItem("hassTokens",JSON.stringify(%s))'%json.dumps(auth));context.add_init_script("window.__rejections=[];addEventListener('unhandledrejection',e=>__rejections.push({keys:Object.keys(e.reason||{}),code:e.reason?.code}));");p=context.new_page();errors=[];p.on('pageerror',lambda e:errors.append({'type':type(e).__name__,'message':re.sub(r'https?://[^\s]+','[url]',str(e)).replace(private['token'],'[redacted]'),'location':re.findall(r'/([A-Za-z0-9_.-]+\.js):(\d+):(\d+)',e.stack or '')}))
 p.goto(base+'/lovelace/0',wait_until='domcontentloaded');p.wait_for_function("!!document.querySelector('home-assistant')?.hass && !!customElements.get('ha-form')")
 p.add_script_tag(content='(function(){'+source+'})();')
 p.evaluate("""()=>{const original=document.querySelector('home-assistant').hass;window.mockCalls=[];const id='light.synthetic';const registry={entity_id:id,device_id:'synthetic',platform:'demo',labels:[]};const device={id:'synthetic',name:'Synthetic device',manufacturer:'Example',model:'Synthetic'};window.__task3Core={labels:new Map(),metrics:{structuralBuilds:0},attach(){},retain(){return()=>{}},watch(){return()=>{}},getEntity(){return {registry}},getDevice(){return device},getDeviceEntities(){return [{registry}]}};window.synthetic={...original,states:{...original.states,[id]:{entity_id:id,state:'on',attributes:{friendly_name:'Synthetic lamp',supported_color_modes:['brightness'],brightness:128}}},entities:{[id]:registry},devices:{synthetic:device},callService:(...args)=>mockCalls.push(args)};const host=document.createElement('main');host.style.cssText='position:fixed;left:-10000px;top:0;width:320px';document.querySelector('home-assistant').shadowRoot.querySelector('home-assistant-main').shadowRoot.append(host);window.host=host;window.card=document.createElement('task3-busch-device-card');card.setConfig({device_id:'synthetic',entity:id,quick_controls:true,start_expanded:true});card.hass=synthetic;host.append(card);window.editor=document.createElement('task3-busch-device-card-editor');editor.setConfig({device_id:'synthetic',quick_controls:true,title:'Original',extra:0});editor.hass=synthetic;host.append(editor);window.events=[];editor.addEventListener('config-changed',e=>{events.push(e.detail.config);editor.setConfig(JSON.parse(JSON.stringify(e.detail.config)))});window.leaks=[];document.addEventListener('keydown',e=>leaks.push(e.key));}""")
 p.wait_for_function("!!editor._form.shadowRoot && !!card.querySelector('hui-tile-card')",timeout=15000)
 p.wait_for_function("""()=>{const deep=root=>{for(const el of root.querySelectorAll('*')){if(el.tagName==='INPUT'&&el.type==='text'&&el.value==='Original')return el;if(el.shadowRoot){const found=deep(el.shadowRoot);if(found)return found;}}};return !!deep(editor._form.shadowRoot)}""")
 p.evaluate("""()=>{const deep=root=>{for(const el of root.querySelectorAll('*')){if(el.tagName==='INPUT'&&el.type==='text'&&el.value==='Original')return el;if(el.shadowRoot){const found=deep(el.shadowRoot);if(found)return found;}}};window.nativeInput=deep(editor._form.shadowRoot);nativeInput.focus();nativeInput.select();}""")
 p.keyboard.type('Native device title',delay=10);p.wait_for_timeout(200)
 result=p.evaluate("""()=>{const typed=events.at(-1)?.title==='Native device title';editor._form.dispatchEvent(new CustomEvent('value-changed',{detail:{value:{...editor._form.data,quick_controls:false,image:'',icon:'mdi:star'}},bubbles:true,composed:true}));const saved=events.at(-1);editor.setConfig(JSON.parse(JSON.stringify(saved)));for(const modifier of ['ctrlKey','metaKey'])nativeInput.dispatchEvent(new KeyboardEvent('keydown',{key:'k',[modifier]:true,bubbles:true,composed:true,cancelable:true}));card._offen=false;card._zeigeListe();const power=card._quick.querySelector('button'),brightness=card._quick.querySelector('input');power.click();brightness.focus();brightness.value='0';brightness.dispatchEvent(new Event('change',{bubbles:true}));brightness.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,composed:true}));const focusBefore=document.activeElement;card.hass={...synthetic,states:{...synthetic.states}};const stable=focusBefore===document.activeElement&&brightness.isConnected;const widths=[320,480,960].map(width=>{host.style.width=width+'px';return {width,overflow:card.scrollWidth>card.clientWidth+1||editor.scrollWidth>editor.clientWidth+1}});return {nativeForm:!!editor._form.shadowRoot,nativeTile:!!card.querySelector('hui-tile-card').shadowRoot,typedTitle:typed,falseSaved:saved.quick_controls===false&&editor._form.data.quick_controls===false,emptySaved:saved.image==='',zeroPreserved:saved.extra===0,fullPayload:saved.device_id==='synthetic'&&saved.title==='Native device title',focusStable:stable,collapsed:!card._offen,shortcutLeaks:leaks.length,mockedServices:mockCalls.map(c=>({domain:c[0],service:c[1],brightness:c[2].brightness})),widths,version:synthetic.config.version};}""")
 p.wait_for_timeout(100);result['pageErrors']=errors;result['rejections']=p.evaluate('window.__rejections');pathlib.Path(sys.argv[3]).write_text(json.dumps(result,indent=2));print(json.dumps(result));assert all(result[k] for k in ['nativeForm','nativeTile','typedTitle','falseSaved','emptySaved','zeroPreserved','fullPayload','focusStable','collapsed']);assert not result['shortcutLeaks'] and not errors and not any(c['overflow'] for c in result['widths']);b.close()
