"""Synthetic network/FRITZ gallery, interaction and native-form wiring. No live services."""
import json,pathlib,sys
from playwright.sync_api import sync_playwright
source=pathlib.Path(sys.argv[1]).read_text();out=pathlib.Path(sys.argv[2]);out.mkdir(parents=True,exist_ok=True)
fixture='''
customElements.define('ha-icon',class extends HTMLElement{connectedCallback(){this.textContent='◇';}});
customElements.define('ha-form',class extends HTMLElement{constructor(){super();this.attachShadow({mode:'open'})}set schema(v){this._schema=v;queueMicrotask(()=>this.draw())}get schema(){return this._schema}set data(v){this._data=v;queueMicrotask(()=>this.draw())}get data(){return this._data}draw(){if(!this._schema||!this._data)return;const style=document.createElement('style');style.textContent=':host{display:block;min-width:0}*{box-sizing:border-box;min-width:0}label{display:grid;gap:4px;margin-bottom:16px;color:var(--primary-text-color);font:inherit}input{font:inherit;color:var(--primary-text-color);background:var(--secondary-background-color);border:0;border-radius:8px;padding:12px;min-height:44px;width:100%}small{color:var(--secondary-text-color);overflow-wrap:anywhere}';this.shadowRoot.replaceChildren(style);for(const s of this._schema){const label=document.createElement('label');label.textContent=this.computeLabel?.(s)||s.name;const input=document.createElement('input');input.value=typeof this._data[s.name]==='object'?JSON.stringify(this._data[s.name]):this._data[s.name]??'';input.addEventListener('input',()=>this.dispatchEvent(new CustomEvent('value-changed',{detail:{value:{...this._data,[s.name]:input.value}},bubbles:true,composed:true})));label.append(input);if(this.computeHelper){const helper=document.createElement('small');helper.textContent=this.computeHelper(s);label.append(helper)}this.shadowRoot.append(label);}}});
window.core=new BuschCardsCore();window.states={};window.entities={};window.devices={router:{id:'router',name:'Ein Router mit einem besonders langen Titel und weiteren Details',model:'Example router',identifiers:[['fritz','router-key']],config_entries:['demo']},client:{id:'client',name:'Example workstation',config_entries:['demo']},ap:{id:'ap',name:'Example access point',config_entries:['demo']}};
window.add=(id,device,uid,state,attrs={})=>{entities[id]={entity_id:id,device_id:device,platform:'fritz',config_entry_id:'demo',unique_id:uid};states[id]={entity_id:id,state,attributes:attrs,last_changed:'2026-09-29T10:00:00Z',last_updated:'2026-09-29T10:00:00Z'};};
add('binary_sensor.wan','router','router-key-is_connected','on');add('button.reboot','router','router-key-reboot','unknown');add('button.reconnect','router','router-key-reconnect','unknown');add('switch.wlan','router','router-key-wi_fi_1','on',{friendly_name:'WLAN mit langem Netzwerknamen'});add('update.firmware','router','router-key-update','on',{supported_features:1,installed_version:'1.0',latest_version:'2.0'});add('sensor.temperature','router','router-key-cpu_temperature','42',{unit_of_measurement:'°C'});add('sensor.uptime','router','router-key-device_uptime','2026-09-29T00:00:00Z');add('sensor.down','router','router-key-kb_s_received','1250.5',{unit_of_measurement:'kB/s'});
for(let i=1;i<=40;i++){const mac='02:00:00:00:00:'+i.toString(16).padStart(2,'0');add('device_tracker.client'+i,'client',mac+'_tracker',i%3?'home':'not_home',{source_type:'router',mac,ip:'192.0.2.'+i,host_name:'example-host-'+i,friendly_name:'Ein Netzwerkclient mit einem besonders langen Namen '+i,...(i%2?{last_time_reachable:'2026-09-29T12:00:00Z'}:{}),...(i%5?{}:{connected_via_device_id:'ap'})});if(i===1){add('switch.internet','client',mac+'_internet_access','on');add('button.wake','client',mac+'_wake_on_lan','unknown');}}
window.fixtureBase=JSON.stringify({states,entities,devices});window.calls=[];window.hass={locale:{language:'de'},user:{is_admin:true},states,entities,devices,callService:async(...args)=>calls.push(args),callWS:async(...args)=>calls.push(args)};core.retain=()=>()=>{};core.watch=()=>()=>{};core.watchDevice=()=>()=>{};core.attach=()=>{};ensureBuschCore=()=>core;
'''
# The test loads the genuine standalone bundle as an ES module, and fixture code in its scope.
with sync_playwright() as pw:
 browser=pw.chromium.launch();page=browser.new_page(viewport={'width':1000,'height':2000});errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content('<style>body{margin:0;font-family:Arial;background:var(--primary-background-color)}ha-card{display:block;border-radius:16px;border:1px solid var(--divider-color)}ha-form{display:grid;gap:8px}label{display:grid;gap:4px}html{--primary-color:#0879d0;--primary-text-color:#212121;--secondary-text-color:#555;--card-background-color:#fff;--primary-background-color:#fff;--secondary-background-color:#eef5fb;--divider-color:#dbe4ed;--success-color:#16864b;--warning-color:#a76900;--error-color:#db4437}</style>')
 page.add_script_tag(type='module',content=source+'\n'+fixture+'\nwindow.fixtureReady=true;');page.wait_for_function('window.fixtureReady===true');cases=[];dom_contract=[]
 for scenario in ['normal','more','empty']:
  result=page.evaluate('''async scenario=>{const c=document.createElement('busch-network-card');c.setConfig({count:scenario==='more'?2:0,...(scenario==='empty'?{filter:{include:[{state:'no_match'}]}}:{})});c.hass=hass;document.body.append(c);await new Promise(r=>setTimeout(r,0));let mutations=0;const observer=new MutationObserver(rows=>mutations+=rows.length);observer.observe(c.shadowRoot,{subtree:true,childList:true,attributes:true,characterData:true});c.hass={...hass,states:{...states,'sensor.unrelated':{entity_id:'sensor.unrelated',state:'42',attributes:{}}}};await new Promise(r=>setTimeout(r,0));observer.disconnect();c.remove();return {scenario,mutations}}''',scenario);dom_contract.append(result)
 assert all(r['mutations']==0 for r in dom_contract),dom_contract
 for dark in [False,True]:
  page.evaluate("dark=>{for(const [key,day,night]of [['--primary-text-color','#212121','#eee'],['--secondary-text-color','#555','#bbb'],['--card-background-color','#fff','#222'],['--primary-background-color','#fff','#171717'],['--secondary-background-color','#eef5fb','#303b47'],['--divider-color','#dbe4ed','#46505b'],['--success-color','#16864b','#71cf94']])document.documentElement.style.setProperty(key,dark?night:day)}",dark)
  for width in [320,480,960]:
   for kind in ['network','fritz-device']:
    for scenario in ['normal','unknown','unavailable','empty','error','many','compact','image-error','image-good','loading']:
     page.evaluate('''({width,kind,scenario})=>{document.querySelectorAll('[data-test-card]').forEach(e=>e.remove());window.calls=[];const data=JSON.parse(fixtureBase);states=data.states;entities=data.entities;devices=data.devices;if(scenario==='empty')for(const id of Object.keys(states))if(id.startsWith('device_tracker.'))delete states[id];if(['unknown','unavailable'].includes(scenario))for(const s of Object.values(states))s.state=scenario;if(scenario==='unknown')for(const s of Object.values(states)){delete s.attributes.ip;s.attributes.last_time_reachable='2099-01-01T00:00:00Z';s.attributes.connected_to='Name is not provenance';}hass={...hass,states,entities,devices};core.seed(hass);const c=document.createElement('busch-'+kind+'-card');c.dataset.testCard='true';c.style.width=width+'px';c.setConfig({device_id:'router',count:scenario==='many'?0:2,layout:scenario==='compact'?'compact':'detailed',...(scenario==='error'?{filter:{include:[{cidr:'bad/99'}]}}:{}),...(scenario.startsWith('image-')?{image:scenario==='image-error'?'data:image/png;base64,broken':'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 40 40%22%3E%3Crect width=%2240%22 height=%2240%22 fill=%22%23808080%22/%3E%3C/svg%3E'}:{})});c.hass=hass;if(scenario==='loading'){const connect=c._connect;c._connect=()=>{};c._core=null;c._shellSignature=null;document.body.append(c);c._render();c._connect=connect;}else document.body.append(c);}''',{'width':width,'kind':kind,'scenario':scenario})
     if scenario=='image-error':page.wait_for_function("!document.querySelector('[data-test-card]').shadowRoot.querySelector('.card-icon img')")
     if scenario=='image-good':page.wait_for_function("document.querySelector('[data-test-card]').shadowRoot.querySelector('.card-icon img')?.naturalWidth>0")
     findings=page.evaluate('''()=>{const c=document.querySelector('[data-test-card]'),bounds=c.getBoundingClientRect(),issues=[];for(const e of c.shadowRoot.querySelectorAll('*')){const b=e.getBoundingClientRect(),s=getComputedStyle(e);if(!b.width||!b.height||s.display==='none')continue;if(b.left<bounds.left-1||b.right>bounds.right+1)issues.push({overflow:e.className});if(e.tagName==='BUTTON'&&(b.width<44||b.height<44))issues.push({touch:e.textContent});if(e.tagName==='BUTTON'&&!e.getAttribute('aria-label'))issues.push({aria:e.textContent});if([...e.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())&&!(s.overflow==='hidden'&&s.textOverflow==='ellipsis')&&(e.scrollWidth>e.clientWidth+1||e.scrollHeight>e.clientHeight+1))issues.push({text:e.textContent});}return issues}''')
     text=page.evaluate("document.querySelector('[data-test-card]').shadowRoot.querySelector('ha-card').innerText")
     if scenario=='normal' and kind=='fritz-device':assert '42 °C' in text and '1.250,5 kB/s' in text and 'CPU-Auslastung' not in text
     if scenario=='normal':assert 'Verbindungspunkt: Unbekannt' in text
     if scenario=='error':assert 'CIDR benötigt' in text
     if scenario=='normal' and width==320 and not dark:
      if kind=='fritz-device':
       page.once('dialog',lambda d:d.dismiss());page.get_by_role('button',name='Neu starten',exact=True).click();assert page.evaluate('calls.length')==0,page.evaluate('JSON.stringify(calls)')
       page.once('dialog',lambda d:d.accept());page.get_by_role('button',name='Neu starten',exact=True).click();assert page.evaluate('calls.at(-1)[1]')=='press'
      page.get_by_role('button',name='Aufwecken',exact=True).first.click();assert page.evaluate('calls.at(-1)[0]')=='button'
      before=page.evaluate("document.querySelector('[data-test-card]')._sectionOpen.get('clients')??true");page.get_by_role('button',name='Details',exact=True).last.click();assert page.evaluate("document.querySelector('[data-test-card]')._sectionOpen.get('clients')??true")==before
     name=f'{kind}-{scenario}-{width}-'+('dark' if dark else 'light')+'.png';page.locator('[data-test-card]').screenshot(path=str(out/name));cases.append({'kind':kind,'scenario':scenario,'width':width,'dark':dark,'findings':findings,'screenshot':name})
 for lang in ['de','en']:
  for width in [320,480,960]:
   for dark in [False,True]:
    for kind in ['network','fritz-device']:
     page.evaluate("""({lang,width,dark,kind})=>{document.querySelectorAll('[data-test-card]').forEach(e=>e.remove());document.documentElement.style.setProperty('--primary-text-color',dark?'#eee':'#212121');document.documentElement.style.setProperty('--card-background-color',dark?'#222':'#fff');document.documentElement.style.setProperty('--secondary-background-color',dark?'#303b47':'#eef5fb');document.documentElement.style.setProperty('--secondary-text-color',dark?'#bbb':'#555');const e=document.createElement('busch-'+kind+'-card-editor');e.dataset.testCard='true';e.style.width=width+'px';e._core=core;e.hass={...hass,locale:{language:lang}};e.setConfig({device_id:'router',title:'Editor example',filter:{include:[{cidr:'192.0.2.0/24',and:[{ip_range:{from:'192.0.2.1',to:'192.0.2.100'}}]}],exclude:[{hostname:'guest-*'}]},actions:[{name:'Example',variant:'secondary',tap_action:{action:'more-info'}}]});e._connect=()=>{};document.body.append(e);for(const d of e.shadowRoot.querySelectorAll('details'))d.open=true;}""",{'lang':lang,'width':width,'dark':dark,'kind':kind})
     findings=page.evaluate("""()=>{const e=document.querySelector('[data-test-card]');return e.scrollWidth>e.clientWidth+1?[{editorOverflow:true}]:[];}""")
     file=f'editor-{kind}-{lang}-{width}-'+('dark' if dark else 'light')+'.png';page.locator('[data-test-card]').screenshot(path=str(out/file));cases.append({'kind':kind+'-editor','lang':lang,'width':width,'dark':dark,'findings':findings,'screenshot':file})
 result={'cases':cases,'pageErrors':errors,'domContract':dom_contract};(out/'report.json').write_text(json.dumps(result,indent=2));print(json.dumps({'cases':len(cases),'findings':sum(len(c['findings'])for c in cases),'errors':errors}));assert not errors and not any(c['findings']for c in cases);browser.close()
