"""Targeted actual DOM regressions for network review; synthetic data, no live calls."""
import ast,json,pathlib,sys
from playwright.sync_api import sync_playwright
source=pathlib.Path(sys.argv[1]).read_text();out=pathlib.Path(sys.argv[2]);out.mkdir(parents=True,exist_ok=True)
module=ast.parse(pathlib.Path(__file__).with_name('network-cards.py').read_text())
fixture=next(ast.literal_eval(n.value) for n in module.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='fixture' for t in n.targets))
with sync_playwright() as pw:
 browser=pw.chromium.launch();page=browser.new_page(viewport={'width':480,'height':1600});errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.set_content('<style>body{margin:0;font-family:Arial}html{--primary-color:#0879d0;--primary-text-color:#eee;--secondary-text-color:#bbb;--card-background-color:#222;--secondary-background-color:#303b47;--divider-color:#46505b;--success-color:#71cf94;--error-color:#db4437}</style>')
 page.add_script_tag(type='module',content=source+'\n'+fixture+'\nwindow.fixtureReady=true');page.wait_for_function('window.fixtureReady');core_setup='''()=>{core.seed(hass);window.events=0;document.addEventListener('hass-more-info',()=>events++);}''';page.evaluate(core_setup);results=[]
 for mode in ['details','tap','hold','double']:
  page.evaluate('''mode=>{document.querySelectorAll('[data-probe]').forEach(n=>n.remove());window.events=0;const action={action:'more-info'};window.config={count:1,...(mode==='details'?{}:{actions:[{name:'Custom',tap_action:action,...(mode==='hold'?{hold_action:action}:{}),...(mode==='double'?{double_tap_action:action}:{})}]})};window.c=document.createElement('busch-network-card');c.dataset.probe='true';c.style.width='320px';c.setConfig(config);c.hass=hass;document.body.append(c);window.button=[...c.shadowRoot.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')===(mode==='details'?'Details':'Custom'));}''',mode)
  button=page.get_by_role('button',name='Details' if mode=='details' else 'Custom',exact=True).first
  def trigger():
   if mode=='hold':button.dispatch_event('pointerdown');page.wait_for_timeout(550);button.dispatch_event('pointerup')
   elif mode=='double':button.dblclick();page.wait_for_timeout(300)
   else:button.click();page.wait_for_timeout(10)
  trigger();before=page.evaluate('events');page.evaluate("mode=>{window.button=[...c.shadowRoot.querySelectorAll('button')].find(b=>b.getAttribute('aria-label')===(mode==='details'?'Details':'Custom'))}",mode);retained=page.evaluate('''()=>{c.setConfig(structuredClone(config));c.setConfig(structuredClone(config));return button.isConnected&&[...c.shadowRoot.querySelectorAll('button')].includes(button)}''');trigger();after=page.evaluate('events');results.append({'mode':mode,'retained':retained,'before':before,'after':after,'pass':retained and before==1 and after==2})
 page.evaluate('''()=>{c.remove();events=0;config={count:1,double_tap_action:{action:'more-info'}};c=document.createElement('busch-network-card');c.dataset.probe='true';c.setConfig(config);c.hass=hass;document.body.append(c)}''');page.get_by_role('button',name='Details',exact=True).first.click();page.evaluate("c.setConfig({...config,title:'Changed'})");page.wait_for_timeout(300);results.append({'mode':'pending-change','events':page.evaluate('events'),'pass':page.evaluate('events===0')})
 page.evaluate('''()=>{c.remove();events=0;c=document.createElement('busch-fritz-device-card');c.dataset.probe='true';c.setConfig({device_id:'router',show_clients:false,show_metrics:false,actions:[{name:'Custom',tap_action:{action:'more-info'}}]});c.hass=hass;document.body.append(c)}''');page.get_by_role('button',name='Custom',exact=True).click();page.evaluate('c.remove();document.body.append(c)');page.get_by_role('button',name='Custom',exact=True).click();results.append({'mode':'reattach-shell','events':page.evaluate('events'),'pass':page.evaluate('events===2')})
 for scenario in ['normal','more','empty']:
  result=page.evaluate('''async scenario=>{c.remove();const n=document.createElement('busch-network-card');n.setConfig({count:scenario==='more'?2:0,...(scenario==='empty'?{filter:{include:[{state:'no_match'}]}}:{})});n.hass=hass;document.body.append(n);let mutations=0;const observer=new MutationObserver(rs=>mutations+=rs.length);observer.observe(n.shadowRoot,{subtree:true,attributes:true,childList:true,characterData:true});n.hass={...hass};await new Promise(r=>setTimeout(r,0));observer.disconnect();n.remove();return {mode:'unrelated-'+scenario,mutations,pass:mutations===0}}''',scenario);results.append(result)
 page.evaluate('''()=>{add('binary_sensor.link','router','router-key-is_linked','off');core.seed(hass);c=document.createElement('busch-fritz-device-card');c.dataset.probe='true';c.style.width='320px';c.setConfig({device_id:'router',show_clients:false,show_metrics:false});c.hass=hass;document.body.append(c)}''');text=page.locator('[data-probe]').last.inner_text();text=page.evaluate("c.shadowRoot.querySelector('ha-card').innerText");results.append({'mode':'wan-separation','pass':'Verbunden' in text and 'WAN-Link' in text and 'Kein Link' in text});page.locator('[data-probe]').last.screenshot(path=str(out/'wan-status-320-dark.png'))
 report={'cases':results,'errors':errors,'calls':page.evaluate('calls.length')};(out/'report.json').write_text(json.dumps(report,indent=2));print(json.dumps(report));browser.close();assert not errors and not report['calls'] and all(r['pass']for r in results)
